name: flutter_meow
description: A flutter meow project made for use case tests.

publish_to: 'none'

version: 1.0.0+1

scripts:
  mobx: fvm flutter pub get & fvm flutter pub run build_runner watch  --delete-conflicting-outputs
  mobd: flutter pub get & flutter pub run build_runner build  --delete-conflicting-outputs
  mobb: flutter pub get & flutter pub run build_runner build
  mobw: fvm flutter pub get & fvm flutter pub run build_runner watch
  build_apk: flutter pub get & flutter build apk -t lib/main_production.dart --release
  build_apk_prod: fvm flutter pub get & fvm flutter build apk --flavor prod -t  lib/main_production.dart --release
  build_ios: flutter pub get &  flutter build ios -t lib/main_production.dart --flavor prod --release
  build_web: flutter pub get & flutter build web -t lib/main_production.dart --release
  test: flutter pub get
  test_error: flutter pub get2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_modular: ^3.4.1+1
  mobx: ^2.0.4
  flutter_mobx: ^2.0.2
  dio: ^4.0.0
  flutter_speed_dial: ^4.3.0
  flutter_dotenv: ^5.0.2
  load: ^1.0.0
  lottie: ^1.1.0
  oktoast: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  mobx_codegen: ^2.0.3
  flutter_modular_test: ^1.0.3
  build_runner: ^2.1.2

flutter:
  uses-material-design: true

  assets:
    - .env
    - resources/lottie_animations/loader_animation1.json
    - resources/lottie_animations/loader_animation2.json
    - resources/lottie_animations/loader_cat.json
    - resources/loading.gif
